name: docker-tests-marklogic-unit-test

services:

  marklogic:
    image: "${MARKLOGIC_IMAGE}"
    platform: linux/amd64
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ${MARKLOGIC_LOGS_VOLUME}:/var/opt/MarkLogic/Logs
    ports:
      - 8000-8003:8000-8003

volumes:
  marklogicLogs:
